# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  workingdays:
    image: workingdays
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5024:5024
    volumes:
      - ./data:/app/data:ro
      - ./Logs:/app/Logs:rw
